name: Push Docker Image on DockerHub
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u cocopaps -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag cocopaps/ci-tools:latest
      - name: Push the Docker image
        run: |
          docker push cocopaps/ci-tools
